// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb8rJygdWK7nACSHhXrdckWI8J70DC8pc',
    appId: '1:836679537624:web:36a8812d71dd6acfd8d8ad',
    messagingSenderId: '836679537624',
    projectId: 'floodsurvival-bb358',
    authDomain: 'floodsurvival-bb358.firebaseapp.com',
    storageBucket: 'floodsurvival-bb358.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv3iOC7ZnUwb41SsWqfyfkpl7Z3h1kaUo',
    appId: '1:836679537624:android:45ac54b87b5dfad7d8d8ad',
    messagingSenderId: '836679537624',
    projectId: 'floodsurvival-bb358',
    storageBucket: 'floodsurvival-bb358.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApUNuCsKMgRTuEZZ-Php7zZ2ebfJQsldE',
    appId: '1:836679537624:ios:8aa087d801db145dd8d8ad',
    messagingSenderId: '836679537624',
    projectId: 'floodsurvival-bb358',
    storageBucket: 'floodsurvival-bb358.firebasestorage.app',
    iosBundleId: 'com.example.floodSurvivalApp',
  );
}
